sudo: required
dist: trusty
language: cpp
compiler: gcc
env:
  global:
    secure: H9VaMgb9wSJ1K4fHGo+5kdfPr+7I+hNPpjcrCLd/pBzlW8K0Tn7b3alzjUqkn8rPDyVmUEiwe5HG2GXx+mUa9LWQL7zRM1xUx4HMReWjk/BIzHIoJ1vVaxOtFPH/VMPMgEfNV6t34eF/OjQZZHN6fM83bw9FY/gEvqgFg6bMiUlIQoJpDgToghz5X6qoE2hviakLHYg8LM7ffCEIan86exeOIHQ0VHIZZjIFVIHCp9hgWeud4E2Cxi8woFVCuo6Z2hYoqFQmcf13LYuupksgGa340zqZP6oc8lk4RGOvlkU7ewS2GtNzCSDKwuMJ31ddxm0slAbgjjTIjMUPCMKtRH+Qk3IWTR7lCssVnLkfKnNxhnWc6IHs/sylE1ZygzVJmPWuCGOnAWP9UwdD5PvFwo3R4207Q8r06cGpJZIkB52b40rDxXztbWPvIu8SHdW7ka6mOnMwYvFwQ/xM02l4pHg+pVM8hdvdlrx0TAuSXE01nLIbONlKAkhBcXWwT/fblClC+HcNSbzt2xvclWNrx/L8qYN6iaESzHgFDVb5D7iD5v0f6sQL0bIMjT5fw4WQwoyALRBF57/KmnBUtUrDSi673mwWVY+/tUToXDYe0wgjxaPCnuDfh3uKLr7RBmpOGvrWQDxkiif/MddmjcXkdxBtLhqpL2CExRUOpb4HTlU=

addons:
  coverity_scan:
    project:
      name: zcobell/qview
      description: Tool for viewing the queue at UND
    notification_email: zachary.cobell@arcadis.com
    build_command_prepend: "/opt/qt59/bin/qmake qview.pro"
    build_command: make
    branch_pattern: master
before_install:
- echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END
  CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
- sudo add-apt-repository --yes ppa:beineri/opt-qt592-trusty
- sudo apt-get update  -qq
- sudo apt-get install -qq libsqlite3-dev libnetcdf-dev
- sudo apt-cache search qt59
- sudo apt-get install -qq qt59base qt59charts-no-lgpl qt59webengine qt59imageformats
  qt59connectivity qt59graphicaleffects qt59script qt59sensors qt59webchannel qt59svg
  qt59xmlpatterns qt59location
- export PATH=/opt/qt59/bin:$PATH
script:
- uname -a
- which qmake
- gcc --version
- g++ --version
- ". /opt/qt59/bin/qt59-env.sh"
- "/opt/qt59/bin/qmake qview.pro"
- make
